version: "3.8"
services:
  chromadb:
    image: chromadb/chroma:0.5.16
    container_name: chromadb
    ports:
      - "8001:8000"
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - ./data/chroma_db:/chroma/chroma_db
